/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountBuyer } from './accountBuyer';
import { AccountSeller } from './accountSeller';


export interface AccountSellerDetailPage {
    total?: number;
    list?: Array<AccountSeller>;
    buyerList?: Array<AccountBuyer>;
}
