/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AccountSellerExport {
    name?: string;
    lastname?: string;
    email?: string;
    documentNumber?: string;
    phoneNumber?: string;
    documentName?: string;
    provinceName?: string;
    locationName?: string;
    businessName?: string;
    addressName?: string;
    countCoupons?: number;
    isVerified?: string;
}
