/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AccountBuyer {
    id?: number;
    name?: string;
    lastname?: string;
    email?: string;
    documentNumber?: string;
    numberInvoice?: string;
    documentId?: number;
    documentName?: string;
    accountTypeName?: string;
    coupons?: Array<string>;
    countCoupons?: number;
}
