/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Coupon {
    id?: number;
    code?: string;
    couponBuyerDate?: Date;
    couponSellerDate?: Date;
    sellerId?: number;
    buyerId?: number;
    buyerName?: string;
    sellerName?: string;
    buyerLastname?: string;
    sellerLastname?: string;
}
