/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CuoponFilter {
    maxResults?: number;
    firstResult?: number;
    total?: number;
    from?: Date;
    to?: Date;
    isBuyer?: boolean;
    isSeller?: boolean;
    code?: string;
    likeNameAndLastname?: string;
}
