/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coupon } from './coupon';


export interface CuoponDetailPage {
    total?: number;
    list?: Array<Coupon>;
}
