/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BusinessName } from './businessName';
import { Location } from './location';
import { Province } from './province';
import { ZipCode } from './zipCode';


export interface ProvinceLocationZipCode {
    id?: number;
    provinces?: Array<Province>;
    locations?: Array<Location>;
    zipcode?: ZipCode;
    businessNames?: Array<BusinessName>;
}
