/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ScheduledLottery {
    id?: number;
    countWinnerBuyers?: number;
    countWinnerSeller?: number;
    isValid?: boolean;
    scheduledDate?: Date;
    createDate?: Date;
    status?: string;
    reprocessed?: boolean;
    reprocess?: boolean;
    publish?: boolean;
}
