/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Winner {
    id?: number;
    name?: string;
    lastname?: string;
    fullAddress?: string;
    position?: number;
    reward?: string;
    scheduledDate?: Date;
    createDate?: Date;
    email?: string;
    provinceName?: string;
    phoneNumber?: string;
    businessName?: string;
    couponCode?: string;
    couponBuyerDate?: Date;
    invoiceNumber?: string;
}
